### ISSUE TITLE
Error of new version of DateEntry widget in tkcalendar module

### ISSUE THREAD

**Issue by yucai2005** [alejandroautalan/pygubu-designer#144]
Hi @alejandroautalan ,

I am trying to use the new verison of tkcalendar DateEntry widget coming with pygubu-designer v0.29.

First, I tried to run the original myapp3.py in [this folder](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/integration_with_tkcalendar/myapp3), it said:
      _Exception: Class "tkcalendarwidgets.dateentry" not mapped_

Then I modified the main.ui in pygubu-designer by using the DateEntry widget coming with the latest verison of pygubu-designer, I got the following error:

_D:\PycharmProjects\pygubu-designer-master\examples\integration_with_tkcalendar\myapp3>python myapp.py
Traceback (most recent call last):
  File "D:\PycharmProjects\pygubu-designer-master\examples\integration_with_tkcalendar\myapp3\myapp.py", line 24, in <module>
    app = MainApp()
  File "D:\PycharmProjects\pygubu-designer-master\examples\integration_with_tkcalendar\myapp3\myapp.py", line 16, in __init__
    self.mainwindow = builder.get_object("mainwindow", master)
  File "C:\Python310\lib\site-packages\pygubu\builder.py", line 161, in get_object
    bobject = self._realize(root, wmeta)
  File "C:\Python310\lib\site-packages\pygubu\builder.py", line 198, in _realize
    child = self._realize(parent, childmeta)
  File "C:\Python310\lib\site-packages\pygubu\builder.py", line 198, in _realize
    child = self._realize(parent, childmeta)
  File "C:\Python310\lib\site-packages\pygubu\builder.py", line 184, in _realize
    self._import_class(wmeta.classname)
  File "C:\Python310\lib\site-packages\pygubu\builder.py", line 173, in _import_class
    importlib.import_module(_module)
  File "C:\Python310\lib\importlib\__init__.py", line 117, in import_module
    if name.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'_
    
Is this a bug?

**Comment by alejandroautalan** [comment]
Hello @yucai2005,
That is an example of integration with other library (in this case tkcalendar) and uses a simple approach (It works if you follow the steps [here](https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Reuse)). I will add comments in the example.

The new plugins supports more properties so its a new implementation and more complex.

You should create a new UI interface to test the new plugin. Remember to install pygubu-designer with:

    pip install pygubu-designer[tkcalendar]

Or for all plugins:

    pip install pygubu-designer[all]

Let me know.
Regards

**Comment by yucai2005** [comment]
Hi @alejandroautalan,

(1) I reinstalled pygubu-designer with:

      `pip install pygubu-designer[all]`

(2) I tested the timerapp [here](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/custom_widget). When I open pygubu-designer, go to Edit > Preferences > Custom Widgets,  add the module timerappwidgets.py to the custom widget builders panel, and restart pygubu-designer, it comes up with the error message:
![image](https://user-images.githubusercontent.com/44183578/185264497-675a6bb5-c41b-425e-81ca-5fa5501a98d7.png)

(3) I tested DateEntry widget coming with the new plugin.
My understanding is that, with the new plugin, there is no need to register the widget builder anymore, as it is already built-in, am I right?

I modified the ui file to use the widget in new plugin. The ui file that I was using is

```
<?xml version='1.0' encoding='utf-8'?>
<interface version="1.2">
  <object class="tk.Toplevel" id="mainwindow">
    <property name="geometry">320x100</property>
    <property name="height">200</property>
    <property name="width">200</property>
    <child>
      <object class="ttk.Frame" id="mainframe">
        <property name="height">200</property>
        <property name="padding">5</property>
        <property name="width">200</property>
        <layout manager="pack">
          <property name="side">top</property>
        </layout>
        <child>
          <object class="ttk.Label" id="Label_1">
            <property name="padding">0 10</property>
            <property name="text" translatable="yes">A tkcalendar DateEntry Widget:</property>
            <layout manager="pack">
              <property name="side">top</property>
            </layout>
          </object>
        </child>
        <child>
          <object class="tkcalendar.DateEntry" id="dateentry_2">
            <layout manager="pack">
              <property name="side">top</property>
            </layout>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>
```

and myapp.py is

```
  import pathlib
  import tkinter.ttk as ttk
  import pygubu
  
  PROJECT_PATH = pathlib.Path(__file__).parent
  PROJECT_UI = PROJECT_PATH / "main.ui"
  
  
  class MainApp:
      def __init__(self, master=None):
          self.builder = builder = pygubu.Builder()
          builder.add_resource_path(PROJECT_PATH)
          builder.add_from_file(PROJECT_UI)
          # Main widget
          self.mainwindow = builder.get_object("mainwindow", master)
          builder.connect_callbacks(self)
  
      def run(self):
          self.mainwindow.mainloop()
  
  
  if __name__ == "__main__":
      app = MainApp()
      app.run()
```
  
When I run myapp,py, it comes up with the same error as in my original post:

  ```
D:\PycharmProjects\pygubu-designer-master\examples\integration_with_tkcalendar\myapp3>python myapp.py
  Traceback (most recent call last):
    File "D:\PycharmProjects\pygubu-designer-master\examples\integration_with_tkcalendar\myapp3\myapp.py", line 24, in <module>
      app = MainApp()
    File "D:\PycharmProjects\pygubu-designer-master\examples\integration_with_tkcalendar\myapp3\myapp.py", line 16, in __init__
      self.mainwindow = builder.get_object("mainwindow", master)
    File "C:\Python310\lib\site-packages\pygubu\builder.py", line 161, in get_object
      bobject = self._realize(root, wmeta)
    File "C:\Python310\lib\site-packages\pygubu\builder.py", line 198, in _realize
      child = self._realize(parent, childmeta)
    File "C:\Python310\lib\site-packages\pygubu\builder.py", line 198, in _realize
      child = self._realize(parent, childmeta)
    File "C:\Python310\lib\site-packages\pygubu\builder.py", line 184, in _realize
      self._import_class(wmeta.classname)
    File "C:\Python310\lib\site-packages\pygubu\builder.py", line 173, in _import_class
      importlib.import_module(_module)
    File "C:\Python310\lib\importlib\__init__.py", line 117, in import_module
      if name.startswith('.'):
  AttributeError: 'NoneType' object has no attribute 'startswith'
```

By the way,  my system is Windows 10, and python version is 3.10.6

**Comment by alejandroautalan** [comment]
Hello, Sorry for the inconvenience.

> (2) I tested the timerapp [here](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/custom_widget). When I open pygubu-designer, go to Edit > Preferences > Custom Widgets, add the module timerappwidgets.py to the custom widget builders panel, and restart pygubu-designer, it comes up with the error message: ![image](https://user-images.githubusercontent.com/44183578/185264497-675a6bb5-c41b-425e-81ca-5fa5501a98d7.png)

My fault! I didn't update the examples for pygubu 0.24

> (3) I tested DateEntry widget coming with the new plugin. My understanding is that, with the new plugin, there is no need to register the widget builder anymore, as it is already built-in, am I right?

Also my fault! Yes you are right.

Now I found the **bug**.  I will try to upload a fix ASAP.

> By the way, my system is Windows 10, and python version is 3.10.6

Thanks for your reports!

Alejandro A.

**Comment by alejandroautalan** [comment]
Uploaded a new pygubu version:

    pip install --upgrade pygubu

Try again and let me know. Should be fixed now.

Regards
Alejandro A.

**Comment by yucai2005** [comment]
Hi @alejandroautalan,

The built-in widget in plugin is working now. Thank you very much for your help.

However, "failed to load custom widget module" error is still there:

![image](https://user-images.githubusercontent.com/44183578/185291047-f671c33f-1fbd-4e08-952c-64f08d8ced63.png)

**Comment by alejandroautalan** [comment]
Hello. Sorry for the late response.

> However, "failed to load custom widget module" error is still there:

Please donwnload the example code again. It should work now.

Regards.
Alejandro A.

**Comment by yucai2005** [comment]
Hi @alejandroautalan,

Thanks very much for your efforts to fix the issue. I've just tried the updated example. The "failed to load custom widget module" error has gone, i.e., I can load the custom widget module from within pygubu-designer, and widget appears in the "My Tkcalendar widgets" tab of the tool bar, it looks perfect in pygubu-designer now.  However, when I run the example in terminal, I get the following error:

```
D:\PycharmProjects\pygubu-designer-master\examples\integration_with_tkcalendar\myapp3>python myapp.py
Traceback (most recent call last):
  File "D:\PycharmProjects\pygubu-designer-master\examples\integration_with_tkcalendar\myapp3\myapp.py", line 29, in <module>
    app = MyApp()
  File "D:\PycharmProjects\pygubu-designer-master\examples\integration_with_tkcalendar\myapp3\myapp.py", line 14, in __init__
    self.mainwindow = builder.get_object("mainwindow", master)
  File "C:\Python310\lib\site-packages\pygubu\builder.py", line 161, in get_object
    bobject = self._realize(root, wmeta)
  File "C:\Python310\lib\site-packages\pygubu\builder.py", line 198, in _realize
    child = self._realize(parent, childmeta)
  File "C:\Python310\lib\site-packages\pygubu\builder.py", line 198, in _realize
    child = self._realize(parent, childmeta)
  File "C:\Python310\lib\site-packages\pygubu\builder.py", line 208, in _realize
    raise Exception(msg)
Exception: Class "tkcalendarwidgets.dateentry" not mapped
```

**Comment by alejandroautalan** [comment]
I see your point. I will review it ASAP.

Thanks.
Alejandro A.

**Comment by yucai2005** [comment]
Hi @alejandroautalan,

It's working now. Thank you so much for your great work!
